const Stands = [
  {
    name: 'Carousel',
    category: 'attraction',
    price: 1500,
    visitors: '120 per minute',
    revenue: '40 coins per minute',
    maintenance: '-24% per minute',
    img: 'carousel',
  },
  {
    name: 'Dodgems',
    category: 'attraction',
    price: 1200,
    visitors: '90 per minute',
    revenue: '40 coins per minute',
    maintenance: '-24% per minute',
    img: 'dodgems',
  },
  {
    name: 'Coconut Shy',
    category: 'stall',
    price: 100,
    visitors: '50 per minute',
    revenue: '50 coins per minute',
    maintenance: '-24% per minute',
    img: 'coconut-shy',
  },
  {
    name: 'Hook a Duck',
    category: 'stall',
    price: 110,
    visitors: '45 per minute',
    revenue: '60 coins per minute',
    maintenance: '-24% per minute',
    img: 'hook-a-duck',
  },
  {
    name: 'Basketball Toss',
    category: 'stall',
    price: 90,
    visitors: '40 per minute',
    revenue: '60 coins per minute',
    maintenance: '-24% per minute',
    img: 'basketball',
  },
  {
    name: 'Hot Dogs',
    category: 'confectionary',
    price: 500,
    visitors: '10 per minute',
    revenue: '100 coins per minute',
    maintenance: '-24% per minute',
    img: 'hot-dog',
  },
  {
    name: 'Pop Corn',
    category: 'confectionary',
    price: 480,
    visitors: '9 per minute',
    revenue: '120 coins per minute',
    maintenance: '-24% per minute',
    img: 'popcorn',
  },
  {
    name: 'Candy Floss',
    category: 'confectionary',
    price: 490,
    visitors: '12 per minute',
    revenue: '80 coins per minute',
    maintenance: '-24% per minute',
    img: 'candy-floss',
  },
];

export default Stands;
